env:
  TERM: xterm-256color


window:
  startup_mode: SimpleFullscreen


key_bindings:
  # Allow tmux ctrl-q leader, see https://github.com/jwilm/alacritty/issues/1359
  - { key: Q, mods: Control, chars: "\x11" }

  # cmd+Enter for the good fullscreen
  - { key: 36, mods: Command, action: ToggleSimpleFullscreen }


font:
  normal:
    family: Fira Code
    style: Light
  bold:
    family: Fira Code
    style: Light
  italic:
    family: Fira Code
    style: Light
  size: 14.0
  offset:
    y: 8


schemes:
  gruvbox_dark: &gruvbox_dark
    primary:
      background: '0x1d2021'
      foreground: '0xebdbb2'
    normal:
      black:   '0x282828'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0xa89984'
    bright:
      black:   '0x928374'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xebdbb2'

  solarized_light: &solarized_light
    primary:
      background: '0xfdf6e3'
      foreground: '0x586e75'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

colors: *gruvbox_dark
