tap "aws/tap"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "warrensbox/tap"

brew "awscli"
brew "direnv"
brew "elm"
brew "fastmod"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnupg"
brew "go"
brew "golangci-lint"
brew "httpie"
brew "jo"
brew "jq"
brew "lazygit"
brew "neovim"
brew "node"
brew "openjdk"
brew "openssl@1.1"
brew "poetry"
brew "pyenv"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup"
brew "sd"
brew "starship"
brew "tealdeer"
brew "tfsec"
brew "tmux"
brew "wasm-pack"
brew "yq"

brew "hashicorp/tap/terraform-ls"
brew "heroku/brew/heroku"
brew "warrensbox/tap/tfswitch"

cask "alacritty"
cask "font-fira-code"
cask "font-fira-code-nerd-font"

instance_eval(File.read("#{ENV['HOME']}/dotfiles/secrets/Brewfile")) if File.exist?("#{ENV['HOME']}/dotfiles/secrets/Brewfile")
