format="""
$directory$env_var$git_branch$git_state$git_status
$status$character\
"""

[env_var]
variable = "DP_ENV"
style = "purple"

[git_branch]
style = "yellow"

[git_status]
format = "[($untracked)](blue)[($modified)](yellow)[($deleted)](red)[($staged)](green) "
conflicted = "✘"
untracked  = "●"
modified   = "●"
staged     = "●"
deleted    = "●"
